export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  HOME: '/home',
  DASHBOARD: '/dashboard',

  ATTENDANCE: '/attendance',
  ATTENDANCE_REPORT: '/attendance/report',

  TASKS: '/tasks',
  MY_TASKS: '/tasks/my',
  TASKS_NEW: '/tasks/new',
  PENDING_TASKS: '/tasks/pending',

  ENQUIRIES_NEW: '/enquiries/new',

  ADD_CUSTOMER: '/addCustomer',
  ADD_ITEM: '/addItem',
  ADD_ITEM_GROUP: '/addItemgroup',
  ADD_TASK: '/addTask',
  ADD_TASK_GROUP: '/addTaskgroup',
  ADD_USER: '/addUser',
  ADD_USER_GROUP: '/addUsergroup',

  ORDERS_NEW: '/orders/new',
  ORDERS_BOARD: '/orders/board',
  ORDER_KANBAN: '/orders/board',
  ORDER_UPDATE: '/orders/:id/update',
  DELIVERY_UPDATE: '/delivery/update/:id',
  CUSTOMER_360: '/customers/:id',

  RECEIPT: '/accounts/receipt',
  PAYMENT: '/accounts/payment',
  CASH_LEDGER: '/accounts/cash-ledger',
  FOLLOWUPS: '/accounts/followups',
  ADD_PAYABLE: '/addPayable',
  ADD_RECEIVABLE: '/addRecievable',

  VENDORS: '/vendors',
  VENDOR_DETAILS: '/vendors/:id',

  WHATSAPP: '/whatsapp',
  WHATSAPP_CLOUD: '/whatsapp',
  WHATSAPP_SEND: '/whatsapp/send',
  WHATSAPP_BULK: '/whatsapp/bulk',

  REPORTS_ORDERS: '/reports/orders',
  REPORTS_TRANSACTIONS: '/reports/transactions',
  REPORTS_CUSTOMERS: '/reports/customers',
  REPORTS_PAYMENTS: '/reports/payments',
  REPORTS_ITEMS: '/reports/items',
  REPORTS_TASKS: '/reports/tasks',
  REPORTS_USERS: '/reports/users',
  REPORTS_VENDORS: '/reports/vendors',

  // legacy aliases still used in old code
  ADD_ORDER: '/addOrder',
  ADD_ORDER_V2: '/addOrder1',
  ADD_ENQUIRY: '/addEnquiry',
  ADD_NOTE: '/addNote',
  ALL_BILLS: '/allBills',
  ALL_TRANSACTION: '/allTransaction',
  ALL_TRANSACTION_1: '/allTransaction1',
  ALL_TRANSACTION_2: '/allTransaction2',
  PAYMENT_REPORT: '/paymentReport',
  PRIORITY_REPORT: '/priorityReport',
  VENDOR_BILLS: '/vendorBills',
  ALL_VENDORS: '/AllVendors',
  CALL_LOGS: '/calllogs',
  FLOW_BUILDER: '/flow-builder',
};

export const ROUTE_ALIASES = {
  HOME_ADMIN: '/adminHome',
  HOME_VENDOR: '/vendorHome',
  HOME_OLD: '/home1',
  ADD_NOTE_LOWER: '/addnote',
  ADD_ORDER_V2_LOWER: '/addorder1',
  PENDING_TASK_LOWER: '/pendingtask',
  ATTENDANCE_REPORT_MIXED: '/Attendance-Report',
  ADD_PAYABLE_TYPO: '/addPayble',
  ALL_TRANSACTION_1_TYPO: '/alltranscation1',
  ALL_TRANSACTION_2_LOWER: '/alltransaction2',
  WHATSAPP_LOGIN: '/WhatsAppLogin',
  WHATSAPP_SESSION: '/WhatsAppSession',
  WHATSAPP_ADMIN: '/WhatsAppAdminPanel',
  FOLLOWUPS_OLD: '/Followups',
};
